---
networks:
  arr_apps:
    driver: bridge

services:       

# ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
# ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
# ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - arr_apps
    volumes:
      - /arr/prowlarr/config:/config
      - /arr/rowlarr/backup:/data/backup
      - ${MEDIA_PATH}downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
    env_file:
      - '.env'
  
# ██████╗ ███████╗ ██████╗██╗   ██╗ ██████╗██╗      █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔════╝██╔════╝╚██╗ ██╔╝██╔════╝██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗  ██║      ╚████╔╝ ██║     ██║     ███████║██████╔╝██████╔╝
# ██╔══██╗██╔══╝  ██║       ╚██╔╝  ██║     ██║     ██╔══██║██╔══██╗██╔══██╗
# ██║  ██║███████╗╚██████╗   ██║   ╚██████╗███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚══════╝ ╚═════╝   ╚═╝    ╚═════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
  
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    hostname: recyclarr
    volumes:
      - /arr/recyclarr/config:/config
    networks:
      - arr_network
    restart: unless-stopped
    env_file:
      - '.env'
      
# ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
# ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
# ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
# ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                                 
      
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - /arr/sonarr/config:/config
      - /arr/sonarr/backup:/data/backup
      - ${MEDIA_PATH}/tv:/data/tv
      - ${MEDIA_PATH}/anime/tv:/data/anime/tv
      - ${MEDIA_PATH}/downloads:/downloads
    networks:
      - arr_network
    ports:
      - 8989:8989
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                              

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - /arr/radarr/config:/config
      - /arr/radarr/backup:/data/backup
      - ${MEDIA_PATH}movies:/data/movies
      - ${MEDIA_PATH}anime/movies:/data/anime/movies
      - ${MEDIA_PATH}downloads:/downloads
    networks:
      - arr_network
    ports:
      - 7878:7878
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██╗     ██╗██████╗  █████╗ ██████╗ ██████╗ 
# ██║     ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██║     ██║██║  ██║███████║██████╔╝██████╔╝
# ██║     ██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                             
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    volumes:
      - /arr/lidarr/config:/config
      - ${MEDIA_PATH}music:/data/musicfolder
      - ${MEDIA_PATH}downloads:/downloads
    networks:
      - arr_network
    ports:
      - 8686:8686
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗ ███████╗ █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗  ███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══╝  ██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║███████╗██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                                                                                                   
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    volumes:
      - /arr/readarr/config:/config
      - ${MEDIA_PATH}eBooks:/data/books
      - ${MEDIA_PATH}downloads:/downloads
    networks:
      - arr_network
    ports:
      - 8787:8787
    restart: unless-stopped
    env_file:
      - '.env'

# ██╗  ██╗ ██████╗ ███╗   ███╗ █████╗ ██████╗ ██████╗ 
# ██║  ██║██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔══██╗
# ███████║██║   ██║██╔████╔██║███████║██████╔╝██████╔╝
# ██╔══██║██║   ██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
        
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /arr/homarr/configs:/app/data/configs
      - /arr/homarr/icons:/app/public/icons
      - /arr/homarr/data:/data
    networks:
      - arr_network
    ports:
      - '7575:7575'
    env_file:
      - '.env'

#      ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗██╗███╗   ██╗
#      ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██║████╗  ██║
#      ██║█████╗  ██║     ██║   ╚████╔╝ █████╗  ██║██╔██╗ ██║
# ██   ██║██╔══╝  ██║     ██║    ╚██╔╝  ██╔══╝  ██║██║╚██╗██║
# ╚█████╔╝███████╗███████╗███████╗██║   ██║     ██║██║ ╚████║
#  ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚═╝     ╚═╝╚═╝  ╚═══╝
     
  # jellyfin:
  #   image: linuxserver/jellyfin
  #   container_name: jellyfin
  #   ports:
  #     - '8096:8096/tcp'   # Jellyfin web interface
  #     - '7359:7359/udp'   # Network discovery
  #     - '1900:1900/udp'   # DLNA port
  #   volumes:
  #     - ${ARRPATH}Jellyfin/config:/config
  #     - ${ARRPATH}Radarr/movies:/data/Movies
  #     - ${ARRPATH}Sonarr/tvshows:/data/TVShows
  #     - ${ARRPATH}Lidarr/music:/data/Music
  #     - ${ARRPATH}Readarr/books:/data/Books
  #   env_file:
  #     - '.env'
  #   restart: unless-stopped

# ███╗   ██╗███████╗██████╗  ██████╗ ███████╗████████╗
# ████╗  ██║╚══███╔╝██╔══██╗██╔════╝ ██╔════╝╚══██╔══╝
# ██╔██╗ ██║  ███╔╝ ██████╔╝██║  ███╗█████╗     ██║   
# ██║╚██╗██║ ███╔╝  ██╔══██╗██║   ██║██╔══╝     ██║   
# ██║ ╚████║███████╗██████╔╝╚██████╔╝███████╗   ██║   
# ╚═╝  ╚═══╝╚══════╝╚═════╝  ╚═════╝ ╚══════╝   ╚═╝   
                                                
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    networks:
      - arr_apps
    ports:
      - 6789:6789
    volumes:
      - /nzb/config:/config
      - ${MEDIA_PATH}movies:/data/movies
      - ${MEDIA_PATH}anime/movies:/data/anime/movies
      - ${MEDIA_PATH}/tv:/data/tv
      - ${MEDIA_PATH}/anime/tv:/data/anime/tv
      - ${MEDIA_PATH}downloads:/downloads #optional
    depends_on:
      - tailscale-arr
    environment:
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=tegbzn6789 #optional
    restart: unless-stopped
    env_file:
      - '.env'
      
  tailscale-arr:
    image: tailscale/tailscale:latest
    hostname: tailscale-arr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /arr/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    env_file:
      - '.env'
#  ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝                                                                                          
                                                                                             
  # qbittorrent:
  #   image: linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   hostname: qbittorrent
  #   restart: unless-stopped
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"
  #   volumes:
  #     - /qbittorrent/config:/config
  #     - ${MEDIA_PATH}downloads:/downloads
  #   ports:
  #     - 8080:8080
  #     - 6881:6881
  #     - 6881:6881/udp
  #   environment:
  #     - WEBUI_PORT=8080
  #     - TORRENTING_PORT=6881
  #   healthcheck:
  #     start_period: 15s
  #   env_file:
  #     - '.env'
